// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYTMdZ8jI1uCHJO3x55x_ur4l8wJ48cs4',
    appId: '1:662754139921:web:7184255bd307e52e9736b0',
    messagingSenderId: '662754139921',
    projectId: 'pizzashop-a054f',
    authDomain: 'pizzashop-a054f.firebaseapp.com',
    storageBucket: 'pizzashop-a054f.appspot.com',
    measurementId: 'G-3CVVXVGE4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdQ7UhxKnLA9WpwjF0ZzQlgiiLsBtRYw',
    appId: '1:662754139921:android:0a68008772aabc4b9736b0',
    messagingSenderId: '662754139921',
    projectId: 'pizzashop-a054f',
    storageBucket: 'pizzashop-a054f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZqpRHn28qHa3qYYSZIXfVBg9DgTTzRM',
    appId: '1:662754139921:ios:3868c9eb8cacd5869736b0',
    messagingSenderId: '662754139921',
    projectId: 'pizzashop-a054f',
    storageBucket: 'pizzashop-a054f.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrZqpRHn28qHa3qYYSZIXfVBg9DgTTzRM',
    appId: '1:662754139921:ios:1225f5eb29513a3c9736b0',
    messagingSenderId: '662754139921',
    projectId: 'pizzashop-a054f',
    storageBucket: 'pizzashop-a054f.appspot.com',
    iosBundleId: 'com.example.pizzaApp.RunnerTests',
  );
}
